# Generated by Django 5.1.4 on 2024-12-20 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, choices=[('Contact', 'Contact'), ('Buyer', 'Buyer'), ('Lead', 'Lead'), ('Nurture', 'Nurture'), ('Closed', 'Closed'), ('Past Client', 'Past Client'), ('Sphere', 'Sphere'), ('Trash', 'Trash')], max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='activity.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('tracking_code', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Inquiry', 'Inquiry'), ('Visited Website', 'Visited Website'), ('Viewed Page', 'Viewed Page'), ('Form Submission', 'Form Submission'), ('Other', 'Other')], max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('page_url', models.URLField(blank=True, null=True)),
                ('page_referrer', models.URLField(blank=True, null=True)),
                ('page_duration', models.IntegerField(blank=True, null=True)),
                ('form_data', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('occured_at', models.DateTimeField(auto_now_add=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.people')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.website')),
            ],
            options={
                'ordering': ['-occured_at'],
            },
        ),
    ]
