# Generated by Django 5.1.4 on 2024-12-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='page_referrer',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
