# Generated by Django 5.1.4 on 2024-12-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activity_language_activity_screen_resolution_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='people',
            name='activity_pe_visitor_3a5507_idx',
        ),
        migrations.RemoveField(
            model_name='people',
            name='language',
        ),
        migrations.RemoveField(
            model_name='people',
            name='screen_resolution',
        ),
        migrations.RemoveField(
            model_name='people',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='people',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='people',
            name='visitor_id',
        ),
        migrations.AddField(
            model_name='people',
            name='device_fingerprints',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
