# Generated by Django 5.1.4 on 2024-12-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_remove_people_activity_pe_visitor_3a5507_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='device_fingerprints',
        ),
        migrations.AddField(
            model_name='people',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['visitor_id'], name='activity_ac_visitor_a237b6_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['occured_at'], name='activity_ac_occured_c65755_idx'),
        ),
        migrations.AddIndex(
            model_name='people',
            index=models.Index(fields=['visitor_id'], name='activity_pe_visitor_3a5507_idx'),
        ),
    ]
