# Generated by Django 5.1.4 on 2024-12-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_remove_people_device_fingerprints_people_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='last_heartbeat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Inquiry', 'Inquiry'), ('Visited Website', 'Visited Website'), ('Viewed Page', 'Viewed Page'), ('Form Submission', 'Form Submission'), ('Heartbeat', 'Heartbeat'), ('Other', 'Other')], max_length=100),
        ),
    ]
