# Generated by Django 5.1.4 on 2024-12-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_activity_last_heartbeat_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Viewed Page', 'Viewed Page'), ('Form Submission', 'Form Submission'), ('Heartbeat', 'Heartbeat'), ('Inquiry', 'Inquiry')], max_length=100),
        ),
    ]
