# Generated by Django 5.1.4 on 2024-12-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_alter_activity_activity_type_alter_activity_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
