# Generated by Django 5.1.4 on 2025-02-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_alter_activity_options_alter_chat_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='last_heartbeat',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='page_duration',
        ),
    ]
