# Generated by Django 5.1.4 on 2025-02-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_remove_activity_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='people',
            name='timezone',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
