# Generated by Django 5.1.4 on 2025-02-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_remove_activity_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='stage',
            field=models.CharField(blank=True, choices=[('Contact', 'Contact'), ('Buyer', 'Buyer'), ('Lead', 'Lead'), ('Nurture', 'Nurture'), ('Closed', 'Closed'), ('Past Client', 'Past Client'), ('Sphere', 'Sphere'), ('Trash', 'Trash')], default='Contact', max_length=100, null=True),
        ),
    ]
